Repository codestates-seb/seb44_main_019, pull requests merged in 2023-07, with the labels that each got.

#56 Feat/ws/tslee/finish chat WS 서버, 채팅기능 완료
  websocket/build.gradle
  websocket/src/main/java/com/shellwe/websocket/WebsocketApplication.java
  websocket/src/main/java/com/shellwe/websocket/config/WebSockConfig.java
  websocket/src/main/java/com/shellwe/websocket/controller/ChatController.java
  websocket/src/main/java/com/shellwe/websocket/dto/ChatMember.java
  websocket/src/main/java/com/shellwe/websocket/dto/ChatMessage.java
  websocket/src/main/java/com/shellwe/websocket/dto/ChatRoom.java
  websocket/src/main/java/com/shellwe/websocket/dto/MemberDto.java
  websocket/src/main/java/com/shellwe/websocket/dto/MessageDto.java
  websocket/src/main/java/com/shellwe/websocket/dto/QueryDto.java
  websocket/src/main/java/com/shellwe/websocket/dto/ResponseDto.java
  websocket/src/main/java/com/shellwe/websocket/dto/RoomDto.java
  websocket/src/main/java/com/shellwe/websocket/entity/Auditable.java
  websocket/src/main/java/com/shellwe/websocket/entity/Member.java
  websocket/src/main/java/com/shellwe/websocket/entity/MemberRoom.java
  websocket/src/main/java/com/shellwe/websocket/entity/Message.java
  websocket/src/main/java/com/shellwe/websocket/entity/Room.java
  websocket/src/main/java/com/shellwe/websocket/entity/Shell.java
  websocket/src/main/java/com/shellwe/websocket/exception/advice/GlobalExceptionAdvice.java
  websocket/src/main/java/com/shellwe/websocket/exception/businessLogicException/BusinessLogicException.java
  websocket/src/main/java/com/shellwe/websocket/exception/businessLogicException/ExceptionCode.java
  websocket/src/main/java/com/shellwe/websocket/exception/errorResponse/ErrorResponse.java
  websocket/src/main/java/com/shellwe/websocket/handler/WebSockChatHandler.java
  websocket/src/main/java/com/shellwe/websocket/mapper/RoomMapper.java
  websocket/src/main/java/com/shellwe/websocket/repository/MemberRepository.java
  websocket/src/main/java/com/shellwe/websocket/repository/MemberRoomRepository.java
  websocket/src/main/java/com/shellwe/websocket/repository/MessageRepository.java
  websocket/src/main/java/com/shellwe/websocket/repository/RoomRepository.java
  websocket/src/main/java/com/shellwe/websocket/service/HttpService.java
  websocket/src/main/java/com/shellwe/websocket/service/Service.java
  websocket/src/main/java/com/shellwe/websocket/service/WsService.java
  websocket/src/main/resources/application.yml
  websocket/src/main/resources/data.sql
  websocket/src/main/resources/schema.sql
Labels: WS

#70 Feat/fe/dwjoo/shell detail
  client/src/App.tsx
  client/src/asset/ellipsis.svg
  client/src/asset/plus.svg
  client/src/asset/poke.svg
  client/src/asset/product.jpg
  client/src/component/DetailPageSidebar/DetailPageSidebar.styled.ts
  client/src/component/DetailPageSidebar/DetailPageSidebar.tsx
  client/src/component/DetailPageSidebar/Toggle.tsx
  client/src/component/OfferModal/OfferModal.styled.ts
  client/src/component/OfferModal/OfferModal.tsx
  client/src/component/ShellDetail/ShellDetail.styled.ts
  client/src/component/ShellDetail/ShellDetail.tsx
  client/src/component/ShellImgPreview/ShellImgPreview.styled.ts
  client/src/component/ShellImgPreview/ShellImgPreview.tsx
  client/src/mock/mock.tsx
  client/src/page/shelldetail/ShellDetailPage.styled.ts
  client/src/page/shelldetail/ShellDetailPage.tsx
  client/src/page/shelllist/ShellList.styled.ts
  client/src/page/shelllist/ShellList.tsx
Labels: Frontend, feat

#78 Feat/fe/dwjoo/home page
  client/src/App.css
  client/src/App.tsx
  client/src/asset/homepage/DM.png
  client/src/asset/homepage/poke.png
  client/src/asset/homepage/poke2.png
  client/src/asset/homepage/shallweshellwe.png
  client/src/asset/homepage/shellwefisrtpage.png
  client/src/component/footer/Footer.styled.ts
  client/src/component/header/Header.styled.ts
  client/src/main.tsx
  client/src/page/home/HomePage.styled.ts
  client/src/page/home/HomePage.tsx
Labels: Frontend, feat

#73 Feat/fe/dwjoo/offered shells
  client/src/App.tsx
  client/src/component/offeredshells/PokedShellList.styled.ts
  client/src/component/offeredshells/PokedShellList.tsx
  client/src/component/offeredshells/ResponseShell.styled.ts
  client/src/component/offeredshells/ResponseShell.tsx
  client/src/component/offeredshells/ResponseShellList.tsx
  client/src/component/offeredshells/ShellInfo.styled.ts
  client/src/component/offeredshells/ShellInfo.tsx
  client/src/page/offeredshells/OfferedShellsPage.styled.ts
  client/src/page/offeredshells/OfferedShellsPage.tsx
Labels: Frontend, feat

#74 Feat/fe/dwjoo/my page
  client/src/App.tsx
  client/src/asset/example.png
  client/src/component/myshells/MyShells.styled.ts
  client/src/component/myshells/MyShells.tsx
  client/src/component/myshells/MyShellsList.styled.ts
  client/src/component/myshells/MyShellsList.tsx
  client/src/component/myshells/ShellsTab.tsx
  client/src/component/profile/ChangePassword.styled.ts
  client/src/component/profile/ChangePassword.tsx
  client/src/component/profile/DeleteProfile.styled.ts
  client/src/component/profile/DeleteProfile.tsx
  client/src/component/profile/EditProfile.styled.ts
  client/src/component/profile/EditProfile.tsx
  client/src/component/profile/ProfileTab.tsx
  client/src/component/profile/profile.styled.ts
  client/src/component/profile/profile.tsx
  client/src/page/mypage/MyPage.styled.tsx
  client/src/page/mypage/MyPage.tsx
  client/src/page/myshells/MyShellsPage.styled.ts
  client/src/page/myshells/MyShellsPage.tsx
Labels: Frontend, feat

#86 Feat/fe/dwjoo/shell detail 전체적 수정
  client/src/App.css
  client/src/App.tsx
  client/src/component/DetailPageSidebar/DetailPageSidebar.tsx
  client/src/component/OfferModal/OfferModal.styled.ts
  client/src/component/OfferModal/OfferModal.tsx
  client/src/component/ShellDetail/DefaultBody.tsx
  client/src/component/ShellDetail/SeeMoreBody.tsx
  client/src/component/ShellDetail/ShellDetail.styled.ts
  client/src/component/ShellDetail/ShellDetail.tsx
  client/src/component/ShellImgPreview/ShellImgPreview.styled.ts
  client/src/component/nav/Nav.styled.ts
  client/src/component/nav/Nav.tsx
  client/src/component/offeredshells/PokedShellList.styled.ts
  client/src/component/offeredshells/ResponseShell.styled.ts
  client/src/component/offeredshells/ResponseShellList.tsx
  client/src/component/offermodal-myshelllist/MyShell.styled.ts
  client/src/component/offermodal-myshelllist/MyShell.tsx
  client/src/component/offermodal-myshelllist/MyShellList.tsx
  client/src/page/directmessage/DirectMessage.styled.ts
  client/src/page/myshells/MyShellsPage.styled.ts
  client/src/page/offeredshells/OfferedShellsPage.styled.ts
  client/src/page/shelldetail/ShellDetailPage.styled.ts
  client/src/style/GlobalStyle.ts
Labels: Frontend, refactor

#98 Test/ws/tslee/test 슬라이스, 유닛 테스트 (http controller, service, jwt)
  server/src/main/resources/application.yml
  websocket/build.gradle
  websocket/src/docs/asciidoc/index.adoc
  websocket/src/main/java/com/shellwe/websocket/entity/MemberRoom.java
  websocket/src/main/resources/application.yml
  websocket/src/main/resources/static/docs/index.html
  websocket/src/test/java/com/shellwe/websocket/customAnnotation/WithMockCustomUser.java
  websocket/src/test/java/com/shellwe/websocket/customAnnotation/WithMockCustomUserSecurityContextFactory.java
  websocket/src/test/java/com/shellwe/websocket/slice/controller/ChatControllerTest.java
  websocket/src/test/java/com/shellwe/websocket/slice/service/HttpServiceTest.java
  websocket/src/test/java/com/shellwe/websocket/unitTest/auth/JwtTokenizerTest.java
  websocket/src/test/java/com/shellwe/websocket/unitTest/auth/MemberDetailsServiceTest.java
  websocket/src/test/resources/org/springframework.restdocs/templates/request-headers.snippet
Labels: WS

#99 [test] 슬라이스, 유닛 테스트 (controller, service, jwt) (#91)
  websocket/src/docs/asciidoc/index.adoc
  websocket/src/main/resources/static/docs/index.html
  websocket/src/test/java/com/shellwe/websocket/customAnnotation/WithMockCustomUser.java
  websocket/src/test/java/com/shellwe/websocket/customAnnotation/WithMockCustomUserSecurityContextFactory.java
  websocket/src/test/java/com/shellwe/websocket/slice/controller/ChatControllerTest.java
  websocket/src/test/java/com/shellwe/websocket/slice/service/HttpServiceTest.java
  websocket/src/test/java/com/shellwe/websocket/unitTest/auth/JwtTokenizerTest.java
  websocket/src/test/java/com/shellwe/websocket/unitTest/auth/MemberDetailsServiceTest.java
  websocket/src/test/resources/org/springframework.restdocs/templates/request-headers.snippet
Labels: WS

#103 Feat/fe/dwjoo/avatar2
  client/src/common/avatar/Avatar.tsx
Labels: Frontend, feat

#106 Feat/fe/dwjoo/my shell page
  client/src/component/myshells/CurrentShells.tsx
  client/src/component/myshells/LikeShells.tsx
  client/src/component/myshells/MyShellsList.styled.ts
  client/src/component/myshells/MyShellsList.tsx
  client/src/component/myshells/PastShells.tsx
  client/src/component/myshells/ShellsTab.tsx
  client/src/component/myshellslist/MyShells.styled.ts
  client/src/component/myshellslist/MyShells.tsx
  client/src/component/myshellslist/MyShellsList.tsx
  client/src/component/offermodal-myshelllist/MyShell.styled.ts
  client/src/component/offermodal-myshelllist/MyShell.tsx
  client/src/component/offermodal-myshelllist/MyShellList.tsx
  client/src/component/profile/ProfileTab.tsx
  client/src/component/profile/profile.styled.ts
  client/src/component/profile/profile.tsx
  client/src/dataset/TypeOfMyShells.ts
  client/src/dataset/queryKey.ts
  client/src/hooks/myshells/useCurrentShells.ts
  client/src/hooks/myshells/useLikeShells.ts
  client/src/hooks/myshells/usePastShells.ts
  client/src/page/mypage/MyPage.tsx
  client/src/page/myshells/MyShellsPage.tsx
Labels: Frontend, feat

#107 Feat/fe/dwjoo/offered page2
  client/src/App.css
  client/src/component/ShellImgPreview/Preview.tsx
  client/src/component/ShellImgPreview/ShellImgPreview.styled.ts
  client/src/component/ShellImgPreview/ShellImgPreview.tsx
  client/src/component/offeredshells/OfferedShell.tsx
  client/src/component/offeredshells/PokedShellList.styled.ts
  client/src/component/offeredshells/PokedShellList.tsx
  client/src/component/offeredshells/ResponseShell.styled.ts
  client/src/component/offeredshells/ResponseShell.tsx
  client/src/component/offeredshells/ResponseShellList.tsx
  client/src/component/offeredshells/ShellInfo.styled.ts
  client/src/component/offeredshells/ShellInfo.tsx
  client/src/dataset/TypesOfferedShell.ts
  client/src/hooks/offer/useAccept.ts
  client/src/hooks/offer/useMyShellsList.ts
  client/src/hooks/offer/useOfferedShellsList.ts
  client/src/page/offeredshells/OfferedShellsPage.styled.ts
  client/src/page/offeredshells/OfferedShellsPage.tsx
  client/src/utill/queryClient.ts
Labels: Frontend, feat

#111 Feat/fe/dwjoo/my page2
  client/package-lock.json
  client/src/component/profile/ChangePassword.styled.ts
  client/src/component/profile/ChangePassword.tsx
  client/src/component/profile/DeleteProfile.styled.ts
  client/src/component/profile/DeleteProfile.tsx
  client/src/component/profile/EditProfile.styled.ts
  client/src/component/profile/EditProfile.tsx
  client/src/component/profile/profile.styled.ts
  client/src/component/profile/profile.tsx
  client/src/dataset/queryKey.ts
  client/src/hooks/profile/useChangePassword.ts
  client/src/hooks/profile/useDeleteMember.ts
  client/src/hooks/profile/useGetMember.ts
  client/src/hooks/profile/useImageUpload.ts
  client/src/hooks/profile/useUpdateMember.ts
  client/src/page/mypage/MyPage.tsx
  client/src/utill/axiosInstance.ts
Labels: Frontend, feat

#114 Feat/fe/dwjoo/shell detail
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/component/DetailPageSidebar/DetailPageSidebar.styled.ts
  client/src/component/DetailPageSidebar/DetailPageSidebar.tsx
  client/src/component/DetailPageSidebar/Toggle.tsx
  client/src/component/OfferModal/OfferModal.tsx
  client/src/component/ShellDetail/DefaultBody.tsx
  client/src/component/ShellDetail/SeeMoreBody.tsx
  client/src/component/ShellDetail/ShellDetail.styled.ts
  client/src/component/ShellDetail/ShellDetail.tsx
  client/src/component/offermodal-myshelllist/MyShell.tsx
  client/src/component/offermodal-myshelllist/MyShellList.tsx
  client/src/dataset/ShellDetailType.ts
  client/src/hooks/shelldetail/useDeleteShells.ts
  client/src/hooks/shelldetail/useGetPokeShellsList.ts
  client/src/hooks/shelldetail/usePatchStateOfShells.ts
  client/src/hooks/shelldetail/usePokeShell.ts
  client/src/hooks/shelldetail/useShellsDetailId.ts
  client/src/hooks/shells/useShellsId.ts
  client/src/mock/mock.tsx
  client/src/page/shelldetail/ShellDetailPage.tsx
  client/src/utill/axiosInstance.ts
Labels: Frontend, feat

#121 Feat/fe/jeongchanyeong/loginsignup
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/common/avatar/Avatar.styled.ts
  client/src/common/shell/Shell.tsx
  client/src/component/OfferModal/OfferModal.tsx
  client/src/component/ShellDetail/DefaultBody.tsx
  client/src/component/ShellDetail/SeeMoreBody.tsx
  client/src/component/ShellDetail/ShellDetail.tsx
  client/src/component/dmlist/DM.tsx
  client/src/component/nav/Nav.styled.ts
  client/src/component/nav/Nav.tsx
  client/src/component/offeredshells/ResponseShell.tsx
  client/src/component/offermodal-myshelllist/MyShell.tsx
  client/src/dataset/queryKey.ts
  client/src/hooks/login/PostLogin.ts
  client/src/hooks/login/PostSignup.ts
  client/src/hooks/offer/useMyPokedShellsList.ts
  client/src/hooks/offer/useOfferedShellsList.ts
  client/src/hooks/shelldetail/useGetPokeShellsList.ts
  client/src/hooks/shelldetail/usePokeShell.ts
  client/src/hooks/shelldetail/useShellsDetailId.ts
  client/src/hooks/shells/useCreateShells.ts
  client/src/hooks/shells/useMainPageShells.ts
  client/src/page/login/GoogleLoginToken.tsx
  client/src/page/login/LoginPage.styled.ts
  client/src/page/login/LoginPage.tsx
  client/src/page/main/MainPage.styled.ts
  client/src/page/main/MainPage.tsx
  client/src/page/mypage/MyPage.tsx
  client/src/page/offeredshells/OfferedShellsPage.tsx
  client/src/page/shelldetail/ShellDetailPage.tsx
  client/src/page/signup/SignupPage.styled.ts
  client/src/page/signup/SignupPage.tsx
  client/src/recoil/atom.ts
  client/src/utill/axiosInstance.ts
  client/src/utill/localstorageData.ts
  client/src/utill/makeBodyText.ts
Labels: bug & fix

#124 Fix/fe/dwjoo/shelldetailoffer
  client/src/App.tsx
  client/src/asset/avatar/defaultpfp.png
  client/src/asset/avatar/defaultprofile.webp
  client/src/asset/avatar/userimg.svg
  client/src/asset/btn_google.png
  client/src/asset/example.png
  client/src/common/tag/TagBox.tsx
  client/src/component/OfferModal/OfferModal.styled.ts
  client/src/component/OfferModal/OfferModal.tsx
  client/src/component/ShellDetail/DefaultBody.tsx
  client/src/component/ShellDetail/SeeMoreBody.tsx
  client/src/component/ShellDetail/ShellDetail.styled.ts
  client/src/component/ShellDetail/ShellDetail.tsx
  client/src/component/ShellImgPreview/ShellImgPreview.styled.ts
  client/src/component/myshellspage-myshellslist/MyShells.tsx
  client/src/component/offeredshells/OfferedShell.tsx
  client/src/component/offeredshells/PokedShellList.tsx
  client/src/component/offeredshells/ResponseShell.styled.ts
  client/src/component/offeredshells/ResponseShell.tsx
  client/src/component/offeredshells/ShellInfo.styled.ts
  client/src/component/offeredshells/ShellInfo.tsx
  client/src/component/offermodal-myshelllist/MyShell.tsx
  client/src/component/offermodal-myshelllist/MyShellList.tsx
  client/src/component/profile/ChangePassword.tsx
  client/src/component/profile/DeleteProfile.tsx
  client/src/component/profile/EditProfile.tsx
  client/src/component/profile/ProfileTab.tsx
  client/src/component/profile/profile.styled.ts
  client/src/component/profile/profile.tsx
  client/src/dataset/TypeOfLogin.ts
  client/src/dataset/TypeOfShellDetail.ts
  client/src/dataset/TypesOfferedShell.ts
  client/src/dataset/queryKey.ts
  client/src/hooks/chat/useChatList.ts
  client/src/hooks/login/PostLogin.ts
  client/src/hooks/login/PostSignup.ts
  client/src/hooks/offer/useAccept.ts
  client/src/hooks/profile/useGetMember.ts
  client/src/hooks/shelldetail/useGetPokeShellsList.ts
  client/src/hooks/shelldetail/usePatchStateOfShells.ts
  client/src/hooks/shelldetail/usePokeShell.ts
  client/src/page/login/GoogleLoginToken.tsx
  client/src/page/login/LoginPage.styled.ts
  client/src/page/login/LoginPage.tsx
  client/src/page/login/OauthFailPage.tsx
  client/src/page/myshells/MyShellsPage.tsx
  client/src/page/offeredshells/OfferedShellsPage.styled.ts
  client/src/page/offeredshells/OfferedShellsPage.tsx
  client/src/page/shelldetail/ShellDetailPage.tsx
  client/src/page/signup/SignupPage.tsx
  client/src/utill/googleLogin.ts
  client/src/utill/handlecancel.ts
Labels: Frontend, bug & fix

#126 Fix/fe/dwjoo/responsive web
  client/src/App.tsx
  client/src/common/avatar/Avatar.styled.ts
  client/src/common/chattextarea/ChatTextArea.styled.ts
  client/src/common/tag/Tag.styled.ts
  client/src/component/DMroom/DMRoom.styled.tsx
  client/src/component/DetailPageSidebar/DetailPageSidebar.tsx
  client/src/component/OfferModal/OfferModal.styled.ts
  client/src/component/OfferModal/OfferModal.tsx
  client/src/component/ShellDetail/ShellDetail.styled.ts
  client/src/component/ShellImgPreview/ShellImgPreview.styled.ts
  client/src/component/ShellImgPreview/ShellImgPreview.tsx
  client/src/component/dmlist/DM.styled.ts
  client/src/component/dmlist/DM.tsx
  client/src/component/header/Header.styled.ts
  client/src/component/myshellspage-myshellslist/MyShells.styled.ts
  client/src/component/myshellspage-myshellslist/MyShellsList.tsx
  client/src/component/offeredshells/OfferedShell.tsx
  client/src/component/offeredshells/PokedShellList.styled.ts
  client/src/component/offeredshells/PokedShellList.tsx
  client/src/component/offeredshells/ResponseShell.styled.ts
  client/src/component/offeredshells/ResponseShell.tsx
  client/src/component/offeredshells/ShellInfo.styled.ts
  client/src/component/offermodal-myshelllist/MyShell.styled.ts
  client/src/component/offermodal-myshelllist/MyShell.tsx
  client/src/component/offermodal-myshelllist/MyShellList.tsx
  client/src/component/profile/ChangePassword.styled.ts
  client/src/component/profile/ChangePassword.tsx
  client/src/component/profile/DeleteProfile.styled.ts
  client/src/component/profile/EditProfile.styled.ts
  client/src/component/profile/ProfileTab.tsx
  client/src/component/profile/profile.styled.ts
  client/src/component/profile/profile.tsx
  client/src/hooks/offer/useAccept.ts
  client/src/page/directmessage/DirectMessage.styled.ts
  client/src/page/home/HomePage.styled.ts
  client/src/page/home/HomePage.tsx
  client/src/page/login/OauthFailPage.tsx
  client/src/page/mypage/MyPage.styled.tsx
  client/src/page/myshells/MyShellsPage.styled.ts
  client/src/page/offeredshells/OfferedShellsPage.styled.ts
  client/src/page/offeredshells/OfferedShellsPage.tsx
  client/src/page/shelldetail/ShellDetailPage.styled.ts
Labels: Frontend, bug & fix
